services:
  apifacta_api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: apifacta-api:latest
    # Se seu fluxo precisa baixar arquivos e você quer ver no host, mapeie uma pasta:
    # volumes:
    #   - ./downloads:/app/downloads
    environment:
      TZ: "${TZ:-America/Sao_Paulo}"
    ports:
      - "8000:8000"
    # A API mantém o container vivo. n8n chama via HTTP POST.
    restart: unless-stopped
